```
import pandas as pd

# Define the path to the XLSX file
file_path = "files/OLD - Composição do Stack Tecnológico de Dados no Cepel_Parte 2 (Avançada)(1-6).xlsx"

# Read the XLSX file into a DataFrame
df = pd.read_excel(file_path)
```

In [12]:
import pandas as pd
import os

# Define the directory where the files are located
directory = "files"

# List of file names (replace placeholders with actual file names)
file_names = [
    "OLD - Composição do Stack Tecnológico de Dados no Cepel_Parte 0 (Identificação)(1-5).xlsx",
    "OLD - Composição do Stack Tecnológico de Dados no Cepel_Parte 1 (Geral)(1-6).xlsx",  # Replace with actual file name
    "OLD - Composição do Stack Tecnológico de Dados no Cepel_Parte 2 (Avançada)(1-6).xlsx",  # Replace with actual file name
    "OLD - Composição do Stack Tecnológico de Dados no Cepel_Parte 3 (Interface DevOps)(1-6).xlsx"   # Replace with actual file name
]

# Dictionary to store DataFrames for each file
dataframes = {}

# Read each file into a separate DataFrame
for file_name in file_names:
    file_path = os.path.join(directory, file_name)
    try:
        df = pd.read_excel(file_path)
        dataframes[file_name] = df
        print("dataframes['{}'] = df".format(file_name))  # Print the variable name and DataFrame
    except FileNotFoundError:
        print(f"File {file_name} not found at {file_path}")
    except Exception as e:
        print(f"Error reading {file_name}: {str(e)}")

# Now you can access each DataFrame using the dictionary
# Example: dataframes['OLD - Composição do Stack Tecnológico de Dados no Cepel_Parte 2 (Avançada)(1-6).xlsx']

dataframes['OLD - Composição do Stack Tecnológico de Dados no Cepel_Parte 0 (Identificação)(1-5).xlsx'] = df
dataframes['OLD - Composição do Stack Tecnológico de Dados no Cepel_Parte 1 (Geral)(1-6).xlsx'] = df
dataframes['OLD - Composição do Stack Tecnológico de Dados no Cepel_Parte 2 (Avançada)(1-6).xlsx'] = df
dataframes['OLD - Composição do Stack Tecnológico de Dados no Cepel_Parte 3 (Interface DevOps)(1-6).xlsx'] = df

In [13]:
dataframes['OLD - Composição do Stack Tecnológico de Dados no Cepel_Parte 0 (Identificação)(1-5).xlsx']

,ID,Hora de início,Hora de conclusão,Email,Nome,Hora da última modificação,Favor inserir seu nome completo.,Favor inserir seu email (@cepel.br).,Em qual departamento do Cepel você está alocado?,Favor apontar sua faixa etária.,Favor apontar o seu tempo de casa no Cepel.,Favor apontar seu maior nível de formação educacional.,Há quanto tempo você já programa / desenvolve sistemas?,"Há quanto tempo você já trabalha com dados (governança, engenharia, ciência, ou análise de dados)?"
0,1,2026-02-02 11:05:31,2026-02-02 11:07:18,0361934@cepel.br,Alberto Pavim,NaN,Alberto Xavier Pavim,alberto.pavim@cepel.br,DT/DID - Depto de IA e Dados,45-54 anos,Menos de 1 ano,Doutorado,5-10 anos,3-5 anos
1,2,2026-02-02 14:22:27,2026-02-02 14:23:43,felipedias@cepel.br,Felipe Dias de Rezende Machado,NaN,Felipe Dias de Rezende Machado,felipedias@cepel.br,"DT/DPC - Depto de Planejamento Energético, Com...",35-44 anos,11-15 anos,Mestrado / MBA,Mais de 10 anos,Mais de 10 anos
2,3,2026-02-03 05:16:19,2026-02-03 05:18:20,0361680@cepel.br,Djalma Silva,NaN,Djalma Lúcio Soares da Silva,djalma.lucio,DT/DID - Depto de IA e Dados,45-54 anos,Menos de 1 ano,Doutorado,Mais de 10 anos,Mais de 10 anos
3,4,2026-02-03 08:32:17,2026-02-03 08:33:26,laao@cepel.br,Luiz Antônio Alves de Oliveira,NaN,Luiz Antonio Alves de Oliveira,laao,DT/DSE - Depto de Sistemas Eletroenergéticos,45-54 anos,16-20 anos,Doutorado,Mais de 10 anos,Mais de 10 anos
4,5,2026-02-20 07:39:48,2026-02-20 07:45:46,0362504@cepel.br,Zhang Yuan,NaN,Zhang Yuan,0362504@cepel.br,DT/DID - Depto de IA e Dados,35-44 anos,Menos de 1 ano,Especialização,5-10 anos,5-10 anos

In [14]:
dataframes['OLD - Composição do Stack Tecnológico de Dados no Cepel_Parte 1 (Geral)(1-6).xlsx']

,ID,Hora de início,Hora de conclusão,Email,Nome,Hora da última modificação,"Estruturados / tabulares (CSV, planilhas, dataframes, SQL dumps)","Semi-estruturados / sem esquema rígido (JSON, TOON, XML, parquet, ORC, Avro)","Não-estruturados / sem formato definido (textos/docs, logs, áudios, imagens, vídeos, binários)",Quais dos seguintes tipos de dados lhe são prioritários?,...,Streamlit,Dash,Shiny,Gradio,Panel,Mercury,Evidence,Outro2,"Se você apontou ter usado, usar atualmente, ou querer usar ""Outro"" framework/ferramenta de análise e visualização de dados acima, por favor identifique qual abaixo.",Quais dos seguintes frameworks/ferramentas de análise e visualização de dados lhe são prioritários?
0,2,2026-02-02 13:20:20,2026-02-02 13:27:28,0361934@cepel.br,Alberto Pavim,NaN,Uso atualmente,Uso atualmente,Já usei,"Estruturados / tabulares (CSV, planilhas, data...",...,Uso atualmente,Não tenho opinião / Não sei,Me interesso em usar,Me interesso em usar,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,NaN,Streamlit;Apache Superset;Trino;
1,3,2026-02-02 14:25:20,2026-02-02 14:41:39,felipedias@cepel.br,Felipe Dias de Rezende Machado,NaN,Uso atualmente,Uso atualmente,Já usei,"Estruturados / tabulares (CSV, planilhas, data...",...,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Já usei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,NaN,PowerBI;Gradio;
2,4,2026-02-03 05:18:40,2026-02-03 05:35:49,0361680@cepel.br,Djalma Silva,NaN,Uso atualmente,Já usei,Uso atualmente,"Estruturados / tabulares (CSV, planilhas, data...",...,Já usei,Já usei,Não tenho opinião / Não sei,Já usei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não preciso / Não se aplica,NaN,Streamlit;Gradio;
3,5,2026-02-03 08:15:04,2026-02-03 08:31:15,laao@cepel.br,Luiz Antônio Alves de Oliveira,NaN,Uso atualmente,Uso atualmente,Uso atualmente,"Estruturados / tabulares (CSV, planilhas, data...",...,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,NaN,Trino;
4,6,2026-02-20 07:46:03,2026-02-20 08:02:27,0362504@cepel.br,Zhang Yuan,NaN,Já usei,Já usei,Já usei,"Semi-estruturados / sem esquema rígido (JSON, ...",...,Já usei,Já usei,Me interesso em usar,Me interesso em usar,Me interesso em usar,Me interesso em usar,Me interesso em usar,Não tenho opinião / Não sei,NaN,PowerBI;Tableau;Qlik;
5,7,2026-02-23 09:40:33,2026-02-23 15:04:12,0361532@cepel.br,Jonathan Cabreira,NaN,Uso atualmente,Já usei,Já usei,"Estruturados / tabulares (CSV, planilhas, data...",...,Já usei,Já usei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,NaN,PowerBI;Tableau;Looker;

In [11]:
dataframes['OLD - Composição do Stack Tecnológico de Dados no Cepel_Parte 2 (Avançada)(1-6).xlsx']

,ID,Hora de início,Hora de conclusão,Email,Nome,Hora da última modificação,Block storage,File storage,Object storage,Quais dos seguintes formatos para armazenamento e gestão de dados lhe são prioritários?,...,"ELK Stack (Elastic, Logstash, Kibana)",Graphite,Fluentd,Splunk,New Relic,Datadog,Ambari,Outro2,"Se você apontou ter usado, usar atualmente, ou querer usar ""Outro"" framework/ferramenta de monitoramento de dados/recursos acima, por favor identifique qual abaixo.",Quais dos seguintes frameworks/ferramentas de monitoramento de dados/recursos lhe são prioritários?
0,1,2026-02-02 13:35:33,2026-02-02 13:48:49,0361934@cepel.br,Alberto Pavim,NaN,Já usei,Uso atualmente,Me interesso em usar,File storage;Object storage;,...,Me interesso em usar,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Me interesso em usar,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Me interesso em usar,Não tenho opinião / Não sei,NaN,"ELK Stack (Elastic, Logstash, Kibana);OpenTele..."
1,2,2026-02-02 14:44:00,2026-02-02 14:49:45,felipedias@cepel.br,Felipe Dias de Rezende Machado,NaN,Já usei,Uso atualmente,Já usei,File storage;Block storage;,...,Já usei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,NaN,"OpenTelemetry;ELK Stack (Elastic, Logstash, Ki..."
2,3,2026-02-03 05:36:07,2026-02-03 05:44:39,0361680@cepel.br,Djalma Silva,NaN,Já usei,Uso atualmente,Não tenho opinião / Não sei,File storage;,...,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Me interesso em usar,Não tenho opinião / Não sei,Não preciso / Não se aplica,NaN,Prometheus;OpenTelemetry;Grafana;
3,4,2026-02-03 08:41:28,2026-02-03 08:50:20,laao@cepel.br,Luiz Antônio Alves de Oliveira,NaN,Já usei,Uso atualmente,Uso atualmente,Object storage;,...,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,NaN,Zabbix;Grafana;
4,5,2026-02-20 08:02:37,2026-02-20 08:28:43,0362504@cepel.br,Zhang Yuan,NaN,Já usei,Já usei,Já usei,Object storage;File storage;,...,Já usei,Me interesso em usar,Me interesso em usar,Me interesso em usar,Já usei,Me interesso em usar,Me interesso em usar,Não tenho opinião / Não sei,NaN,"New Relic;ELK Stack (Elastic, Logstash, Kibana..."
5,6,2026-02-23 09:40:39,2026-02-23 14:15:06,0361532@cepel.br,Jonathan Cabreira,NaN,Não tenho opinião / Não sei,Já usei,Já usei,Object storage;File storage;,...,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Já usei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,NaN,Grafana;

In [15]:
dataframes['OLD - Composição do Stack Tecnológico de Dados no Cepel_Parte 3 (Interface DevOps)(1-6).xlsx']

,ID,Hora de início,Hora de conclusão,Email,Nome,Hora da última modificação,Windows NT Server,Windows 10/11,"Linux Debian (Ubuntu, Mint, Kali)","Linux Arch (Manjaro, EndeavourOS)",...,reStructuredText (reST),Sphinx,MkDocs,Read the Docs,Keep a Changelog,Scribe,OBS Studio,Outro8,"Se você apontou ter usado, usar atualmente, ou querer usar ""Outro"" framework/ferramenta de documentação de projetos/software/dados acima, por favor identifique qual abaixo.",Quais dos seguintes frameworks/ferramentas de documentação de projetos/software/dados lhe são prioritários?
0,1,2026-02-02 13:51:53,2026-02-02 14:09:32,0361934@cepel.br,Alberto Pavim,NaN,Já usei,Uso atualmente,Uso atualmente,Não tenho opinião / Não sei,...,Me interesso em usar,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Me interesso em usar,Me interesso em usar,Já usei,Me interesso em usar,Não tenho opinião / Não sei,NaN,MS Teams;MS Sharepoint;Swagger;Ckan;Read the D...
1,2,2026-02-02 14:53:07,2026-02-02 15:02:20,felipedias@cepel.br,Felipe Dias de Rezende Machado,NaN,Já usei,Uso atualmente,Uso atualmente,Me interesso em usar,...,Uso atualmente,Uso atualmente,Uso atualmente,Uso atualmente,Uso atualmente,Não tenho opinião / Não sei,Já usei,Não tenho opinião / Não sei,NaN,MS Teams;PlantUML;reStructuredText (reST);Keep...
2,3,2026-02-03 05:44:54,2026-02-03 05:59:35,0361680@cepel.br,Djalma Silva,NaN,Já usei,Uso atualmente,Uso atualmente,Já usei,...,Já usei,Já usei,Uso atualmente,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Já usei,Não preciso / Não se aplica,NaN,MS Teams;MkDocs;Draw.io;
3,4,2026-02-03 08:51:12,2026-02-03 09:17:01,laao@cepel.br,Luiz Antônio Alves de Oliveira,NaN,Já usei,Uso atualmente,Uso atualmente,Não tenho opinião / Não sei,...,Não tenho opinião / Não sei,Já usei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Já usei,Não tenho opinião / Não sei,NaN,MS Teams;MS Sharepoint;Sphinx;
4,5,2026-02-20 08:28:54,2026-02-20 08:35:55,0362504@cepel.br,Zhang Yuan,NaN,Já usei,Já usei,Já usei,Já usei,...,Me interesso em usar,Me interesso em usar,Me interesso em usar,Me interesso em usar,Me interesso em usar,Me interesso em usar,Já usei,Não tenho opinião / Não sei,NaN,Confluence;Miro;Slack;Draw.io;Swagger;
5,6,2026-02-23 14:15:22,2026-02-23 14:27:34,0361532@cepel.br,Jonathan Cabreira,NaN,Não tenho opinião / Não sei,Já usei,Já usei,Não tenho opinião / Não sei,...,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Não tenho opinião / Não sei,Já usei,Não tenho opinião / Não sei,NaN,Confluence;Draw.io;Miro;

In [21]:
import pandas as pd
import sqlite3
import os

# Define the directory where the files are located
directory = "files"

# List of file names
file_names = [
    "OLD - Composição do Stack Tecnológico de Dados no Cepel_Parte 0 (Identificação)(1-5).xlsx",
    "OLD - Composição do Stack Tecnológico de Dados no Cepel_Parte 1 (Geral)(1-6).xlsx",
    "OLD - Composição do Stack Tecnológico de Dados no Cepel_Parte 2 (Avançada)(1-6).xlsx",
    "OLD - Composição do Stack Tecnológico de Dados no Cepel_Parte 3 (Interface DevOps)(1-6).xlsx"
]

# Create a connection to an SQLite database (this will create a new database if it doesn't exist)
db_path = "cepel_data.db"
conn = sqlite3.connect(db_path)
print(f"Connected to SQLite database at {db_path}")

# Read each Excel file and load it into the SQLite database as a separate table
for file_name in file_names:
    file_path = os.path.join(directory, file_name)
    try:
        # Read the Excel file into a pandas DataFrame
        df = pd.read_excel(file_path)
        
        # Create a table name from the file name (remove special characters and spaces)
        table_name = file_name.replace(" ", "_").replace("(", "").replace(")", "").replace("-", "_").split(".")[0]
        
        # Write the DataFrame to the SQLite database as a table
        df.to_sql(table_name, conn, if_exists='replace', index=False)
        print(f"Successfully loaded {file_name} into table {table_name}")
    except FileNotFoundError:
        print(f"File {file_name} not found at {file_path}")
    except Exception as e:
        print(f"Error processing {file_name}: {str(e)}")

Connected to SQLite database at cepel_data.db
Successfully loaded OLD - Composição do Stack Tecnológico de Dados no Cepel_Parte 0 (Identificação)(1-5).xlsx into table OLD___Composição_do_Stack_Tecnológico_de_Dados_no_Cepel_Parte_0_Identificação1_5
Successfully loaded OLD - Composição do Stack Tecnológico de Dados no Cepel_Parte 1 (Geral)(1-6).xlsx into table OLD___Composição_do_Stack_Tecnológico_de_Dados_no_Cepel_Parte_1_Geral1_6
Successfully loaded OLD - Composição do Stack Tecnológico de Dados no Cepel_Parte 2 (Avançada)(1-6).xlsx into table OLD___Composição_do_Stack_Tecnológico_de_Dados_no_Cepel_Parte_2_Avançada1_6
Successfully loaded OLD - Composição do Stack Tecnológico de Dados no Cepel_Parte 3 (Interface DevOps)(1-6).xlsx into table OLD___Composição_do_Stack_Tecnológico_de_Dados_no_Cepel_Parte_3_Interface_DevOps1_6

In [23]:
import pandas as pd
import sqlite3
import os

# Define the directory where the files are located
directory = "files"

# List of file names
file_names = [
    "OLD - Composição do Stack Tecnológico de Dados no Cepel_Parte 0 (Identificação)(1-5).xlsx",
    "OLD - Composição do Stack Tecnológico de Dados no Cepel_Parte 1 (Geral)(1-6).xlsx",
    "OLD - Composição do Stack Tecnológico de Dados no Cepel_Parte 2 (Avançada)(1-6).xlsx",
    "OLD - Composição do Stack Tecnológico de Dados no Cepel_Parte 3 (Interface DevOps)(1-6).xlsx"
]

# Create or connect to the SQLite database
db_path = "cepel_data.db"
conn = sqlite3.connect(db_path)
print(f"Connected to SQLite database at {db_path}")

# Read each Excel file and load it into the SQLite database as a separate table
for file_name in file_names:
    file_path = os.path.join(directory, file_name)
    try:
        # Read the Excel file into a pandas DataFrame
        df = pd.read_excel(file_path)
        
        # Create a table name from the file name (remove special characters and spaces)
        table_name = file_name.replace(" ", "_").replace("(", "").replace(")", "").replace("-", "_").split(".")[0]
        
        # Write the DataFrame to the SQLite database as a table
        df.to_sql(table_name, conn, if_exists='replace', index=False)
        print(f"Successfully loaded {file_name} into table {table_name}")
    except FileNotFoundError:
        print(f"File {file_name} not found at {file_path}")
    except Exception as e:
        print(f"Error processing {file_name}: {str(e)}")

# Check all tables in the database to confirm their names
cursor = conn.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()
print("\nTables in the database:")
for table in tables:
    print(table[0])

Connected to SQLite database at cepel_data.db
Successfully loaded OLD - Composição do Stack Tecnológico de Dados no Cepel_Parte 0 (Identificação)(1-5).xlsx into table OLD___Composição_do_Stack_Tecnológico_de_Dados_no_Cepel_Parte_0_Identificação1_5
Successfully loaded OLD - Composição do Stack Tecnológico de Dados no Cepel_Parte 1 (Geral)(1-6).xlsx into table OLD___Composição_do_Stack_Tecnológico_de_Dados_no_Cepel_Parte_1_Geral1_6
Successfully loaded OLD - Composição do Stack Tecnológico de Dados no Cepel_Parte 2 (Avançada)(1-6).xlsx into table OLD___Composição_do_Stack_Tecnológico_de_Dados_no_Cepel_Parte_2_Avançada1_6
Successfully loaded OLD - Composição do Stack Tecnológico de Dados no Cepel_Parte 3 (Interface DevOps)(1-6).xlsx into table OLD___Composição_do_Stack_Tecnológico_de_Dados_no_Cepel_Parte_3_Interface_DevOps1_6

Tables in the database:
OLD___Composição_do_Stack_Tecnológico_de_Dados_no_Cepel_Parte_0_Identificação1_5
OLD___Composição_do_Stack_Tecnológico_de_Dados_no_Cepel_Parte_1_Geral1_6
OLD___Composição_do_Stack_Tecnológico_de_Dados_no_Cepel_Parte_2_Avançada1_6
OLD___Composição_do_Stack_Tecnológico_de_Dados_no_Cepel_Parte_3_Interface_DevOps1_6

In [26]:
for table in tables:
    print(table)

('OLD___Composição_do_Stack_Tecnológico_de_Dados_no_Cepel_Parte_0_Identificação1_5',)
('OLD___Composição_do_Stack_Tecnológico_de_Dados_no_Cepel_Parte_1_Geral1_6',)
('OLD___Composição_do_Stack_Tecnológico_de_Dados_no_Cepel_Parte_2_Avançada1_6',)
('OLD___Composição_do_Stack_Tecnológico_de_Dados_no_Cepel_Parte_3_Interface_DevOps1_6',)

In [27]:
# Example: Query the first few rows from the first available table (if any)
if tables:
    example_table = tables[0][0]  # Take the first table name from the list
    print(f"\nQuerying the first few rows from table: {example_table}")

Querying the first few rows from table: OLD___Composição_do_Stack_Tecnológico_de_Dados_no_Cepel_Parte_0_Identificação1_5

```
Você cria:

conn → conexão com o banco

cursor → objeto que executa comandos SQL

Ele executa SQL diretamente no arquivo do banco, sem HTTP, sem JSON, sem requisição externa.
```

In [24]:
# Example: Query the first few rows from the first available table (if any)
if tables:
    example_table = tables[0][0]  # Take the first table name from the list
    try:
        cursor.execute(f"SELECT * FROM {example_table} LIMIT 5")
        rows = cursor.fetchall()
        columns = [description[0] for description in cursor.description]
        print(f"\nFirst 5 rows from table {example_table}:")
        print(columns)
        for row in rows:
            print(row)
    except Exception as e:
        print(f"Error querying table {example_table}: {str(e)}")
else:
    print("\nNo tables found in the database. Please check if the files were loaded correctly.")

First 5 rows from table OLD___Composição_do_Stack_Tecnológico_de_Dados_no_Cepel_Parte_0_Identificação1_5:
['ID', 'Hora de início', 'Hora de conclusão', 'Email', 'Nome', 'Hora da última modificação', 'Favor inserir seu\xa0nome completo.', 'Favor inserir seu\xa0email\xa0(@cepel.br).', 'Em qual\xa0departamento\xa0do Cepel você está alocado?', 'Favor apontar sua\xa0faixa etária.', 'Favor apontar o seu\xa0tempo de casa\xa0no Cepel.', 'Favor apontar seu maior nível de\xa0formação educacional.', 'Há quanto tempo você já\xa0programa\xa0/\xa0desenvolve sistemas?', 'Há quanto tempo você já\xa0trabalha com dados\xa0(governança, engenharia, ciência, ou análise de dados)?']
(1, '2026-02-02 11:05:31', '2026-02-02 11:07:18', '0361934@cepel.br', 'Alberto Pavim', None, 'Alberto Xavier Pavim', 'alberto.pavim@cepel.br', 'DT/DID - Depto de IA e Dados', '45-54 anos', 'Menos de 1 ano', 'Doutorado', '5-10 anos', '3-5 anos')
(2, '2026-02-02 14:22:27', '2026-02-02 14:23:43', 'felipedias@cepel.br', 'Felipe Dias de Rezende Machado', None, 'Felipe Dias de Rezende Machado', 'felipedias@cepel.br', 'DT/DPC - Depto de Planejamento Energético, Comercialização de Energia e Regulação', '35-44 anos', '11-15 anos', 'Mestrado / MBA', 'Mais de 10 anos', 'Mais de 10 anos')
(3, '2026-02-03 05:16:19', '2026-02-03 05:18:20', '0361680@cepel.br', 'Djalma Silva', None, 'Djalma Lúcio Soares da Silva', 'djalma.lucio', 'DT/DID - Depto de IA e Dados', '45-54 anos', 'Menos de 1 ano', 'Doutorado', 'Mais de 10 anos', 'Mais de 10 anos')
(4, '2026-02-03 08:32:17', '2026-02-03 08:33:26', 'laao@cepel.br', 'Luiz Antônio Alves de Oliveira', None, 'Luiz Antonio Alves de Oliveira', 'laao', 'DT/DSE - Depto de Sistemas Eletroenergéticos', '45-54 anos', '16-20 anos', 'Doutorado', 'Mais de 10 anos', 'Mais de 10 anos')
(5, '2026-02-20 07:39:48', '2026-02-20 07:45:46', '0362504@cepel.br', 'Zhang Yuan', None, 'Zhang Yuan', '0362504@cepel.br', 'DT/DID - Depto de IA e Dados', '35-44 anos', 'Menos de 1 ano', 'Especialização', '5-10 anos', '5-10 anos')

# I've got db and reading as dataframe

In [ ]:
# Example: Query the first few rows from the first available table (if any) and return as DataFrame
if tables:
    example_table = tables[0][0]  # Take the first table name from the list
    try:
        # Use pandas to directly read the SQL query result into a DataFrame
        df = pd.read_sql_query(f"SELECT * FROM {example_table} LIMIT 5", conn)
        print(f"\nFirst 5 rows from table {example_table} as a DataFrame:")
        display(df)  # Use display() for better formatting in Jupyter Notebook
    except Exception as e:
        print(f"Error querying table {example_table}: {str(e)}")
else:
    print("\nNo tables found in the database. Please check if the files were loaded correctly.")

# Analysing

In [ ]:
example_table = tables[0][0]  # Take the first table name from the list

df = pd.read_sql_query(f"SELECT * FROM {example_table} LIMIT 5", conn)
print(f"\nFirst 5 rows from table {example_table} as a DataFrame:")
display(df)  # Use display() for better formatting in Jupyter Notebook

In [ ]:
example_table = tables[1][0]  # Take the first table name from the list

df = pd.read_sql_query(f"SELECT * FROM {example_table} LIMIT 5", conn)
print(f"\nFirst 5 rows from table {example_table} as a DataFrame:")
display(df)  # Use display() for better formatting in Jupyter Notebook